name: Build Github Pages
on: [push, pull_request]
env:
  PIP: python -m pip
  SPHINX: python -m sphinx --color
jobs:
  configure-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
  build-pages:
    runs-on: macos-latest
    needs: configure-pages
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install pandoc
      run: |
        brew install pandoc
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Double-check Python version
      run: |
        python --version
    - name: Install Python package
      run: |
        $PIP install .[docs]
    - name: Build HTML
      run: |
        $SPHINX docs/ _build/html/
    - name: Create Pages artifact
      run: |
        tar -czf github-pages.tar.gz _build/html
  deploy:
      permissions:
        contents: read
        pages: write
        id-token: write
      runs-on: ubuntu-latest
      needs: build-pages
      environment:
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}
      steps:
        - name: Deploy artifact
          id: deployment
          uses: actions/deploy-pages@v1
