name: Lint

on:
  push:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # TODO replace following steps by single pre-commit stage
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ubuntu-python3.10
      - name: Install dependencies
        run: |
            pip install -e .[dev]
      - name: pip freeze
        run: pip freeze
      - name: Ruff linter
        run: |
          ruff check . --fix --exit-non-zero-on-fix
          ruff format . --check
