name: Run unit-tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        include:
          - os: ubuntu-latest
            run_always: 'true'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
            pip install -e .[test]
      - name: Run unit tests
        if: env.SHOULD_RUN
        run: pytest
